# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
use_frameworks!

target 'UrDailyStep' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  pod 'SwiftyJSON', '3.0.0'
  pod 'Alamofire', '~> 4.0'
  pod 'TextFieldEffects'
  pod 'BEMCheckBox'
  # Pods for UrDailyStep

end
